title: Raymond's Build Guide
description: Build guide and tips for stuff I've discovered along the way
theme: just-the-docs

url: https://raymondagena.github.io/3D-Guide

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/raymondagena/3D-Guide
